version: "3.8"

services:
  pm:
    build: .
    volumes:
      - ./:/app
  server:
    build: .
    volumes:
      - ./:/app
    command: ["uvicorn", "passwordmanager.server.main:app", "--reload", "--host=0.0.0.0", "--port=8000"]
    ports:
      - 8000:8000
  poetry:
    build: .
    volumes:
      - ./:/app
    entrypoint: poetry